# GitHub CI build pipeline
name: Cookiecutter PyPackage CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@5.6.0
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv pip install --upgrade '.[all]'
      - name: Run Tests
        run: |
          pytest
      - name: Run package creation
        run: |
          pre-commit run --all-files
#      - name: Archive package
#        uses: actions/upload-artifact@v2
#        with:
#          name: cookie-cutter
#          path: src/dist
